// react/app/components/Certificates.tsx
import { motion } from 'motion/react';
import { Award, ExternalLink } from 'lucide-react';
import { Card } from './ui/card';
import { Badge } from './ui/badge';

const certificates = [
  {
    title: 'NestJS Authentication',
    issuer: 'Plataforma Online',
    category: 'Backend',
    description: 'Autenticación y autorización con NestJS',
    color: 'from-red-500 to-pink-500'
  },
  {
    title: 'NestJS Modular Programming',
    issuer: 'Plataforma Online',
    category: 'Backend',
    description: 'Programación modular con NestJS',
    color: 'from-red-500 to-pink-500'
  },
  {
    title: 'NestJS TypeORM',
    issuer: 'Plataforma Online',
    category: 'Backend',
    description: 'ORM y gestión de bases de datos con TypeORM',
    color: 'from-red-500 to-pink-500'
  },
  {
    title: 'Backend with NestJS',
    issuer: 'Plataforma Online',
    category: 'Backend',
    description: 'Desarrollo backend completo con NestJS',
    color: 'from-red-500 to-pink-500'
  },
  {
    title: 'NestJS MongoDB',
    issuer: 'Plataforma Online',
    category: 'Backend',
    description: 'Integración de MongoDB con NestJS',
    color: 'from-red-500 to-pink-500'
  },
  {
    title: 'Ethical Hacking',
    issuer: 'Plataforma Online',
    category: 'Hacking',
    description: 'Fundamentos de hacking ético',
    color: 'from-purple-500 to-indigo-500'
  },
  {
    title: 'Pentesting',
    issuer: 'Plataforma Online',
    category: 'Hacking',
    description: 'Pruebas de penetración y seguridad',
    color: 'from-purple-500 to-indigo-500'
  },
  {
    title: 'Social Engineering',
    issuer: 'Plataforma Online',
    category: 'Hacking',
    description: 'Ingeniería social y seguridad',
    color: 'from-purple-500 to-indigo-500'
  },
  {
    title: 'Web Hacking',
    issuer: 'Plataforma Online',
    category: 'Hacking',
    description: 'Seguridad en aplicaciones web',
    color: 'from-purple-500 to-indigo-500'
  },
  {
    title: 'Python Fundamentals',
    issuer: 'Plataforma Online',
    category: 'Programming',
    description: 'Fundamentos de programación en Python',
    color: 'from-blue-500 to-cyan-500'
  },
  {
    title: 'Comprehensions, Functions & Error Handling',
    issuer: 'Plataforma Online',
    category: 'Programming',
    description: 'Python avanzado y manejo de errores',
    color: 'from-blue-500 to-cyan-500'
  },
  {
    title: 'AWS Cloud Practitioner',
    issuer: 'Amazon Web Services',
    category: 'Programming',
    description: 'Fundamentos de AWS Cloud',
    color: 'from-orange-500 to-yellow-500'
  },
  {
    title: 'Web Development Path',
    issuer: 'Plataforma Online',
    category: 'Programming',
    description: 'Ruta completa de desarrollo web',
    color: 'from-green-500 to-emerald-500'
  },
  {
    title: 'Programming from Zero',
    issuer: 'Plataforma Online',
    category: 'Programming',
    description: 'Fundamentos de programación',
    color: 'from-gray-500 to-slate-500'
  }
];

const categories = ['Todos', 'Backend', 'Hacking', 'Programming'];

export function Certificates() {
  const [selectedCategory, setSelectedCategory] = React.useState('Todos');

  const filteredCertificates = selectedCategory === 'Todos'
    ? certificates
    : certificates.filter(cert => cert.category === selectedCategory);

  return (
    <section id="certificados" className="py-20 px-4 bg-white">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Certificaciones
          </h2>
          <p className="text-gray-600 max-w-2xl mx-auto mb-8">
            Formación continua en tecnologías modernas, seguridad informática y buenas prácticas de desarrollo.
          </p>

          {/* Category filters */}
          <div className="flex flex-wrap justify-center gap-3">
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => setSelectedCategory(category)}
                className={`px-6 py-2 rounded-full font-medium transition-all ${
                  selectedCategory === category
                    ? 'bg-gradient-to-r from-purple-600 to-blue-600 text-white shadow-lg'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {category}
              </button>
            ))}
          </div>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredCertificates.map((cert, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.05 }}
            >
              <Card className="p-6 h-full hover:shadow-xl transition-all hover:-translate-y-1 border-2 border-transparent hover:border-purple-200">
                <div className="flex items-start justify-between mb-4">
                  <div className={`bg-gradient-to-r ${cert.color} w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0`}>
                    <Award className="w-6 h-6 text-white" />
                  </div>
                  <Badge variant="outline" className="text-xs">
                    {cert.category}
                  </Badge>
                </div>

                <h3 className="font-bold mb-2 text-lg">{cert.title}</h3>
                <p className="text-sm text-gray-600 mb-3">{cert.issuer}</p>
                <p className="text-sm text-gray-500">{cert.description}</p>

                <button 
                  className="mt-4 text-purple-600 hover:text-purple-700 text-sm font-medium flex items-center gap-2 group"
                  onClick={() => alert('Certificado verificado ✓')}
                >
                  Ver certificado
                  <ExternalLink className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </button>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// React import for useState
import * as React from 'react';

// src/app/certificates/certificates.component.ts
import { Component } from '@angular/core';
import { faAward, faArrowUpRightFromSquare } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-certificates',
  templateUrl: './certificates.component.html',
  styleUrls: ['./certificates.component.css'],
})
export class CertificatesComponent {
  faAward = faAward;
  faExternalLink = faArrowUpRightFromSquare;

  categories = ['Todos', 'Backend', 'DevOps', 'Hacking', 'Programming'];
  selectedCategory = 'Todos';

  categoryTaglines: { [key: string]: string } = {
    'Todos': 'Cada certificado de aquí es una pieza del rompecabezas: una habilidad concreta que hoy sostiene los proyectos que construyo.',
    'Backend': 'Toda gran aplicación tiene un motor que nadie ve, pero que sostiene todo lo que sí se ve. Aquí está el mío, afinado capa por capa.',
    'DevOps': '¿De qué sirve una aplicación brillante si se queda encerrada en mi laptop? Angular y Firebase me dieron el hosting; Docker, las cajas para llevarla a cualquier lugar sin que se rompa en el camino.',
    'Hacking': '¿De qué me sirve construir una casa hermosa si al final no le pongo una puerta segura? Por eso estos certificados: para pensar como quien ataca y así defender mejor lo que construyo.',
    'Programming': 'Antes de correr hay que aprender a caminar —y a probar que cada paso funciona—. Estas son las bases sobre las que construyo todo lo demás, sin atajos.',
  };

  get categoryTagline(): string {
    return this.categoryTaglines[this.selectedCategory] || '';
  }

  allCerts = [
    { title: 'Backend with NestJS', issuer: 'Platzi', category: 'Backend', description: 'Desarrollo backend completo con NestJS', gradient: 'linear-gradient(to right,#ef4444,#ec4899)', img: './assets/BackendConNestjs_certificado.jpg' },
    { title: 'NestJS Modular Programming', issuer: 'Platzi', category: 'Backend', description: 'Programación modular con NestJS', gradient: 'linear-gradient(to right,#ef4444,#ec4899)', img: './assets/nestJS_programacionModular.jpg' },
    { title: 'NestJS TypeORM', issuer: 'Platzi', category: 'Backend', description: 'ORM y gestión de bases de datos', gradient: 'linear-gradient(to right,#ef4444,#ec4899)', img: './assets/nestJsTypeorm.jpg' },
    { title: 'NestJS MongoDB', issuer: 'Platzi', category: 'Backend', description: 'Integración de MongoDB con NestJS', gradient: 'linear-gradient(to right,#ef4444,#ec4899)', img: './assets/NestJS-MongoDB.jpg' },
    { title: 'NestJS Authentication', issuer: 'Platzi', category: 'Backend', description: 'Autenticación y autorización con NestJS', gradient: 'linear-gradient(to right,#ef4444,#ec4899)', img: './assets/nest auth.jpg' },
    { title: 'Firebase con Angular 20', issuer: 'Platzi', category: 'DevOps', description: 'Hosting y despliegue de aplicaciones Angular en Firebase', gradient: 'linear-gradient(to right,#f97316,#facc15)', img: './assets/Firabase con angular 20.jpg' },
    { title: 'Fundamentos de Docker', issuer: 'Platzi', category: 'DevOps', description: 'Contenedores, imágenes y despliegue portable de aplicaciones', gradient: 'linear-gradient(to right,#0ea5e9,#2563eb)', img: './assets/Fundamentos docker.jpg' },
    { title: 'Docker Avanzado', issuer: 'Platzi', category: 'DevOps', description: 'Orquestación, redes y buenas prácticas con contenedores', gradient: 'linear-gradient(to right,#0ea5e9,#2563eb)', img: './assets/Docker Avanzado.jpg' },
    { title: 'Ethical Hacking', issuer: '', category: 'Hacking', description: 'Fundamentos de hacking ético', gradient: 'linear-gradient(to right,#7c3aed,#4f46e5)', img: './assets/hack etico.jpg' },
    { title: 'Pentesting', issuer: '', category: 'Hacking', description: 'Pruebas de penetración y seguridad', gradient: 'linear-gradient(to right,#7c3aed,#4f46e5)', img: './assets/hack pentesting.jpg' },
    { title: 'Social Engineering', issuer: '', category: 'Hacking', description: 'Ingeniería social y seguridad', gradient: 'linear-gradient(to right,#7c3aed,#4f46e5)', img: './assets/hack social.jpg' },
    { title: 'Web Hacking', issuer: '', category: 'Hacking', description: 'Seguridad en aplicaciones web', gradient: 'linear-gradient(to right,#7c3aed,#4f46e5)', img: './assets/hack web.jpg' },
    { title: 'Python Fundamentals', issuer: 'Platzi', category: 'Programming', description: 'Fundamentos de programación en Python', gradient: 'linear-gradient(to right,#3b82f6,#06b6d4)', img: './assets/FundamentosPy_certificado.jpg' },
    { title: 'Comprehensions, Functions & Error Handling', issuer: 'Platzi', category: 'Programming', description: 'Python avanzado y manejo de errores', gradient: 'linear-gradient(to right,#3b82f6,#06b6d4)', img: './assets/FuncionesPy_certificados.jpg' },
    { title: 'AWS Cloud Practitioner', issuer: 'AWS', category: 'Programming', description: 'Fundamentos de AWS Cloud', gradient: 'linear-gradient(to right,#f97316,#eab308)', img: './assets/aws.jpg' },
    { title: 'Web Development Path', issuer: 'EDteam', category: 'Programming', description: 'Ruta completa de desarrollo web', gradient: 'linear-gradient(to right,#22c55e,#10b981)', img: './assets/RutaDesarrolloWeb.jpeg' },
    { title: 'Programming from Zero', issuer: 'EDteam', category: 'Programming', description: 'Fundamentos de programación', gradient: 'linear-gradient(to right,#6b7280,#475569)', img: './assets/programacionCero_certificado.jpeg' },
    { title: 'Fundamentos de Pruebas de Software', issuer: 'Platzi', category: 'Programming', description: 'Testing y aseguramiento de calidad del software', gradient: 'linear-gradient(to right,#3b82f6,#06b6d4)', img: './assets/Fundamentos de pruebas de software.jpg' },
  ];

  get filteredCerts() {
    return this.selectedCategory === 'Todos'
      ? this.allCerts
      : this.allCerts.filter(c => c.category === this.selectedCategory);
  }
}

<section class="py-20 px-4 bg-white">
  <div class="max-w-6xl mx-auto">

    <div animateOnScroll class="text-center mb-16">
      <h2 class="text-4xl font-bold mb-4 gradient-text">Certificaciones</h2>
      <p class="text-gray-600 max-w-2xl mx-auto mb-8">
        Formación continua en tecnologías modernas, seguridad informática y buenas prácticas de desarrollo.
      </p>
      <div class="flex flex-wrap justify-center gap-3 mb-6">
        <button
          *ngFor="let cat of categories"
          (click)="selectedCategory = cat"
          [class]="selectedCategory === cat
            ? 'px-6 py-2 rounded-full font-medium text-white shadow-lg bg-gradient-to-r from-purple-600 to-blue-600'
            : 'px-6 py-2 rounded-full font-medium bg-gray-100 text-gray-700 hover:bg-gray-200 transition-all'"
        >
          {{ cat }}
        </button>
      </div>
      <p class="text-sm text-gray-500 max-w-2xl mx-auto italic">
        {{ categoryTagline }}
      </p>
    </div>

    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div
        *ngFor="let cert of filteredCerts"
        class="bg-white rounded-xl p-6 border-2 border-transparent hover:border-purple-200 hover:shadow-xl hover:-translate-y-1 transition-all flex flex-col shadow-md"
      >
        <div class="flex items-start justify-between mb-4">
          <div class="w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0" [style.background]="cert.gradient">
            <fa-icon [icon]="faAward" class="text-white text-lg"></fa-icon>
          </div>
          <span class="text-xs px-2 py-1 rounded-full border border-gray-300 text-gray-600">{{ cert.category }}</span>
        </div>
        <h3 class="font-bold mb-1 text-lg">{{ cert.title }}</h3>
        <p class="text-sm text-gray-500 mb-2">{{ cert.issuer }}</p>
        <p class="text-sm text-gray-500 flex-1">{{ cert.description }}</p>
        <a [href]="cert.img" target="_blank"
          class="mt-4 text-purple-600 hover:text-purple-700 text-sm font-medium flex items-center gap-2 group">
          Ver certificado
          <fa-icon [icon]="faExternalLink" class="group-hover:translate-x-1 transition-transform text-xs"></fa-icon>
        </a>
      </div>
    </div>

  </div>
</section>
