// src/app/navbar/navbar.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  isScrolled = false;
  menuOpen = false;

  navItems = [
    { label: 'Inicio', id: 'inicio' },
    { label: 'Sobre Mí', id: 'sobre-mi' },
    { label: 'Proyectos', id: 'proyectos' },
    { label: 'Experiencia', id: 'experiencia' },
    { label: 'Habilidades', id: 'habilidades' },
    { label: 'Certificados', id: 'certificados' },
    { label: 'Contacto', id: 'contacto' },
  ];

  @HostListener('window:scroll')
  onScroll() {
    this.isScrolled = window.scrollY > 50;
  }

  scrollToSection(id: string): void {
    if (id === 'inicio') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } else {
      const el = document.getElementById(id);
      el?.scrollIntoView({ behavior: 'smooth' });
    }
    this.menuOpen = false;
  }

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }
}

<nav class="navbar-container" [class.scrolled]="isScrolled">
  <div class="max-w-6xl mx-auto px-4 py-4">
    <div class="flex items-center justify-between">
      <button (click)="scrollToSection('inicio')" class="text-2xl font-bold gradient-text">
        GC
      </button>

      <!-- Desktop -->
      <div class="hidden md:flex items-center gap-6">
        <button
          *ngFor="let item of navItems"
          (click)="scrollToSection(item.id)"
          class="text-gray-700 hover:text-purple-600 transition-colors font-medium text-sm"
        >
          {{ item.label }}
        </button>
      </div>

      <!-- Mobile toggle -->
      <button class="md:hidden p-2" (click)="toggleMenu()">
        <span class="block w-6 h-0.5 bg-gray-700 mb-1"></span>
        <span class="block w-6 h-0.5 bg-gray-700 mb-1"></span>
        <span class="block w-6 h-0.5 bg-gray-700"></span>
      </button>
    </div>
  </div>
</nav>

<!-- Mobile menu -->
<div *ngIf="menuOpen" class="mobile-menu">
  <div class="flex flex-col p-4 space-y-4">
    <button
      *ngFor="let item of navItems"
      (click)="scrollToSection(item.id)"
      class="text-left text-lg font-medium text-gray-700 hover:text-purple-600 transition-colors py-2"
    >
      {{ item.label }}
    </button>
  </div>
</div>

// react/app/components/Navbar.tsx
import { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { Menu, X } from 'lucide-react';
import { Button } from './ui/button';

const navItems = [
  { label: 'Inicio', href: '#inicio' },
  { label: 'Sobre Mí', href: '#sobre-mi' },
  { label: 'Proyectos', href: '#proyectos' },
  { label: 'Experiencia', href: '#experiencia' },
  { label: 'Habilidades', href: '#habilidades' },
  { label: 'Certificados', href: '#certificados' },
  { label: 'Contacto', href: '#contacto' }
];

export function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (href: string) => {
    const sectionId = href.replace('#', '');
    if (sectionId === 'inicio') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    } else {
      const element = document.getElementById(sectionId);
      element?.scrollIntoView({ behavior: 'smooth' });
    }
    setIsMobileMenuOpen(false);
  };

  return (
    <>
      <motion.nav
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
          isScrolled 
            ? 'bg-white/95 backdrop-blur-sm shadow-md' 
            : 'bg-transparent'
        }`}
      >
        <div className="max-w-6xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <button 
              onClick={() => scrollToSection('#inicio')}
              className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent"
            >
              GC
            </button>

            {/* Desktop Navigation */}
            <div className="hidden md:flex items-center gap-6">
              {navItems.map((item, index) => (
                <button
                  key={index}
                  onClick={() => scrollToSection(item.href)}
                  className="text-gray-700 hover:text-purple-600 transition-colors font-medium text-sm"
                >
                  {item.label}
                </button>
              ))}
            </div>

            {/* Mobile Menu Button */}
            <Button
              variant="ghost"
              size="icon"
              className="md:hidden"
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            >
              {isMobileMenuOpen ? (
                <X className="w-6 h-6" />
              ) : (
                <Menu className="w-6 h-6" />
              )}
            </Button>
          </div>
        </div>
      </motion.nav>

      {/* Mobile Menu */}
      {isMobileMenuOpen && (
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -20 }}
          className="fixed inset-0 z-40 bg-white md:hidden"
          style={{ top: '72px' }}
        >
          <div className="flex flex-col p-4 space-y-4">
            {navItems.map((item, index) => (
              <button
                key={index}
                onClick={() => scrollToSection(item.href)}
                className="text-left text-lg font-medium text-gray-700 hover:text-purple-600 transition-colors py-2"
              >
                {item.label}
              </button>
            ))}
          </div>
        </motion.div>
      )}
    </>
  );
}
