// src/app/projects/projects.component.ts
import { Component } from '@angular/core';
import { faRocket, faImages, faXmark, faChevronLeft, faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css'],
})
export class ProjectsComponent {
  faRocket = faRocket;
  faGithub = faGithub;
  faImages = faImages;
  faXmark = faXmark;
  faChevronLeft = faChevronLeft;
  faChevronRight = faChevronRight;

  projects = [
    { title: 'Sistema Asistencias - CAC Santa Elena', description: 'Aplicación web con Firestore en tiempo real que optimizó el control de asistencias. 161K lecturas, 5.9K escrituras, reemplazando el seguimiento manual en Excel.', technologies: ['Firestore','Real-time','Cloud Functions','Web App'], period: '2024-07 / 2024-10', images: ['./assets/attendance1.png', './assets/attendance2.png', './assets/attendance3.png', './assets/attendance4.jpg'] },
    { title: 'Sistema de Monitoreo ECG - VITECED', description: 'Sistema para adquisición y visualización de señales ECG en tiempo real con IoT. Módulo de análisis estadístico para detectar falsos positivos con más de 50K registros.', technologies: ['IoT','ECG','Real-time Analytics','Database','Statistics'], period: '2025-03 / 2025-09', images: ['./assets/teced_ECG.PNG', './assets/teced_ECG falsos positivos.PNG', './assets/teced_datos.png'] },
    { title: 'Sistema de Gestión - FACSISTEL', description: 'Sistema de gestión de reportes e incidencias técnicas para el área de TI de la universidad, desde la concepción hasta el despliegue en servidores.', technologies: ['Angular','NestJS','MySQL','Git','Deployment'], period: '2024-11 / 2025-02', images: ['./assets/upse_dashboard.png', './assets/upse_manual.png', './assets/upse_reporte.png', './assets/upse_reportes.png'] },
    { title: 'Sistema de Reportes - AGUAPEN', description: 'Sistema de reportes operativos para la empresa de agua potable de Manglaralto, con visualización de datos y apoyo en facturación electrónica con el SRI.', technologies: ['Angular','Express','MySQL','Git','SRI Integration'], period: '2024-03 / 2024-06', images: ['./assets/jaapman_reporte 1.jpg', './assets/jaapman_reporte 2.jpg', './assets/jaapman_reporte 3.jpg', './assets/jaapman_reporte 4.jpg'] },
    { title: 'Sistema de Gestión Hotelera', description: 'Aplicación de escritorio con SQL Server, FXML y Java para gestión de reservas de habitaciones, facturación y reportes.', technologies: ['Java','FXML','SQL Server','Desktop App'], period: 'Proyecto Personal', url: 'https://github.com/GustavoCisnerosMatias/projectHotel/tree/main' },
    { title: 'Sistema Arcane Restaurant', description: 'App para gestión de mesas en restaurante con pedidos por QR. Ionic + Angular en frontend, Fat-Free como backend y MySQL.', technologies: ['Ionic','Angular','Fat-Free','PHP','MySQL','QR Code'], period: 'Proyecto Personal', url: 'https://github.com/GustavoCisnerosMatias/Arcane' },
  ];

  selectedProject: (typeof this.projects)[number] | null = null;
  currentImageIndex = 0;

  openProject(p: (typeof this.projects)[number]) {
    this.selectedProject = p;
    this.currentImageIndex = 0;
  }

  closeProject() {
    this.selectedProject = null;
  }

  prevImage() {
    if (!this.selectedProject?.images) return;
    const total = this.selectedProject.images.length;
    this.currentImageIndex = (this.currentImageIndex - 1 + total) % total;
  }

  nextImage() {
    if (!this.selectedProject?.images) return;
    const total = this.selectedProject.images.length;
    this.currentImageIndex = (this.currentImageIndex + 1) % total;
  }

  goToImage(index: number) {
    this.currentImageIndex = index;
  }
}

<section class="py-20 px-4 bg-gradient-to-b from-gray-50 to-white">
  <div class="max-w-6xl mx-auto">

    <div animateOnScroll class="text-center mb-16">
      <h2 class="text-4xl font-bold mb-4 gradient-text">Proyectos Destacados</h2>
      <p class="text-gray-600 max-w-2xl mx-auto">
        Una selección de mis trabajos más recientes en desarrollo de software. Cada proyecto representa
        un desafío único y una oportunidad de crear soluciones eficientes e innovadoras.
      </p>
      <p class="text-gray-500 text-sm max-w-2xl mx-auto mt-4 italic">
        Los primeros fueron productos privados —desarrollados a medida para instituciones y empresas reales—,
        así que su código pertenece a sus dueños; pero aquí puedes ver capturas, historias y el impacto que tuvieron.
        Los dos últimos sí son míos de principio a fin: proyectos personales, mi terreno de práctica, más antiguos
        pero con el código abierto por si quieres curiosear cómo empecé.
      </p>
    </div>

    <div class="grid md:grid-cols-2 gap-8">
      <div *ngFor="let p of projects; let i = index"
           animateOnScroll [animDelay]="i * 100"
           class="bg-white rounded-xl shadow-md hover:shadow-xl transition-shadow overflow-hidden flex flex-col">
        <div class="p-6 flex-1 flex flex-col">
          <div class="flex flex-wrap gap-2 mb-3">
            <span *ngFor="let tech of p.technologies"
              class="px-3 py-1 text-xs bg-gray-100 text-gray-700 rounded-full">
              {{ tech }}
            </span>
          </div>
          <h3 class="text-xl font-bold mb-2">{{ p.title }}</h3>
          <p class="text-gray-600 text-sm mb-4 flex-1">{{ p.description }}</p>
          <p class="text-xs text-gray-400 mb-4">{{ p.period }}</p>
          <div class="flex gap-3">
            <button *ngIf="p.images" (click)="openProject(p)"
              class="flex-1 text-center px-4 py-2 rounded-lg border border-gray-300 text-gray-700 text-sm hover:border-purple-400 hover:text-purple-600 transition-all flex items-center justify-center gap-2">
              <fa-icon [icon]="faImages"></fa-icon> Ver más
            </button>
            <a *ngIf="p.url" [href]="p.url" target="_blank"
              class="flex-1 text-center px-4 py-2 rounded-lg border border-gray-300 text-gray-700 text-sm hover:border-purple-400 hover:text-purple-600 transition-all flex items-center justify-center gap-2">
              <fa-icon [icon]="faGithub"></fa-icon> Código
            </a>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Modal de galería del proyecto -->
  <div *ngIf="selectedProject"
       (click)="closeProject()"
       class="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4">
    <div (click)="$event.stopPropagation()"
         class="bg-white rounded-xl shadow-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto">

      <div class="flex items-start justify-between p-6 pb-0">
        <h3 class="text-xl font-bold pr-4">{{ selectedProject.title }}</h3>
        <button (click)="closeProject()"
                class="flex-shrink-0 w-9 h-9 rounded-full flex items-center justify-center text-gray-500 hover:bg-gray-100 hover:text-gray-700 transition-all">
          <fa-icon [icon]="faXmark"></fa-icon>
        </button>
      </div>

      <div class="px-6 pt-4" *ngIf="selectedProject.images?.length">
        <div class="relative rounded-lg overflow-hidden bg-gray-100">
          <img [src]="selectedProject.images![currentImageIndex]"
               [alt]="selectedProject.title"
               class="w-full max-h-[420px] object-contain bg-gray-100">

          <button *ngIf="selectedProject.images!.length > 1" (click)="prevImage()"
                  class="absolute left-2 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/80 hover:bg-white shadow flex items-center justify-center text-gray-700 transition-all">
            <fa-icon [icon]="faChevronLeft"></fa-icon>
          </button>
          <button *ngIf="selectedProject.images!.length > 1" (click)="nextImage()"
                  class="absolute right-2 top-1/2 -translate-y-1/2 w-9 h-9 rounded-full bg-white/80 hover:bg-white shadow flex items-center justify-center text-gray-700 transition-all">
            <fa-icon [icon]="faChevronRight"></fa-icon>
          </button>
        </div>

        <div class="flex justify-center gap-2 mt-3" *ngIf="selectedProject.images!.length > 1">
          <button *ngFor="let img of selectedProject.images; let i = index"
                  (click)="goToImage(i)"
                  [class]="i === currentImageIndex
                    ? 'w-2.5 h-2.5 rounded-full bg-purple-600 transition-all'
                    : 'w-2.5 h-2.5 rounded-full bg-gray-300 hover:bg-gray-400 transition-all'">
          </button>
        </div>
      </div>

      <div class="p-6">
        <p class="text-gray-600 text-sm mb-4">{{ selectedProject.description }}</p>
        <div class="flex flex-wrap gap-2 mb-2">
          <span *ngFor="let tech of selectedProject.technologies"
            class="px-3 py-1 text-xs bg-gray-100 text-gray-700 rounded-full">
            {{ tech }}
          </span>
        </div>
        <p class="text-xs text-gray-400">{{ selectedProject.period }}</p>
      </div>
    </div>
  </div>

</section>

// react/app/components/Projects.tsx
import { motion } from 'motion/react';
import { ExternalLink, Github } from 'lucide-react';
import { Card } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import { ImageWithFallback } from './figma/ImageWithFallback';

const projects = [
  {
    title: 'Sistema Asistencias - CAC Santa Elena',
    description: 'Aplicación web con Firestore en tiempo real que optimizó el control de asistencias. Se registraron 161K lecturas, 5.9K escrituras y 500 eliminaciones, reemplazando el seguimiento manual en Excel y mejorando significativamente los tiempos de registro.',
    image: 'https://images.unsplash.com/photo-1595079836278-25b7ad6d5ddb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhdHRlbmRhbmNlJTIwc3lzdGVtJTIwUVIlMjBjb2RlJTIwbW9iaWxlfGVufDF8fHx8MTc3NjMxMTgyN3ww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['Firestore', 'Real-time', 'Cloud Functions', 'Web App'],
    period: '2024-07 / 2024-10',
    github: 'https://github.com',
    demo: 'https://example.com'
  },
  {
    title: 'Sistema de Monitoreo ECG - VITECED',
    description: 'Sistema para adquisición y visualización de señales ECG en tiempo real con IoT. Desarrollé módulo de análisis estadístico para detectar falsos positivos con más de 50K registros, asegurando mediciones confiables desde dispositivos IoT.',
    image: 'https://images.unsplash.com/photo-1766299892693-2370a8d47e23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxFQ0clMjBtb25pdG9yaW5nJTIwc3lzdGVtJTIwbWVkaWNhbCUyMHRlY2hub2xvZ3l8ZW58MXx8fHwxNzc2MzExODI3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['IoT', 'ECG', 'Real-time Analytics', 'Database', 'Statistics'],
    period: '2025-03 / 2025-09',
    github: 'https://github.com',
    demo: 'https://example.com'
  },
  {
    title: 'Sistema de Gestión - FACSISTEL',
    description: 'Implementé un sistema de gestión de reportes e incidencias técnicas para el área de TI de la universidad, desde la concepción hasta el despliegue en servidores, asegurando un entorno seguro, escalable y en producción.',
    image: 'https://images.unsplash.com/photo-1752742111841-f490c48aa668?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb3Zlcm5tZW50JTIwSVQlMjBpbmZyYXN0cnVjdHVyZSUyMHNlcnZlcnN8ZW58MXx8fHwxNzc2MzExODI4fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['Angular', 'Express', 'MySQL', 'Git', 'Deployment'],
    period: '2024-11 / 2025-02',
    github: 'https://github.com',
    demo: 'https://example.com'
  },
  {
    title: 'Sistema de Reportes - AGUAPEN',
    description: 'Colaboré en el desarrollo de un sistema de reportes operativos para la empresa de agua potable de Manglaralto, participando en la generación y visualización de datos, y apoyando en la facturación electrónica con el SRI.',
    image: 'https://images.unsplash.com/photo-1763718528755-4bca23f82ac3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjB3ZWIlMjBhcHBsaWNhdGlvbiUyMGRhc2hib2FyZHxlbnwxfHx8fDE3NzYyNTU1Nzd8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['Angular', 'Express', 'MySQL', 'Git', 'SRI Integration'],
    period: '2024-03 / 2024-06',
    github: 'https://github.com',
    demo: 'https://example.com'
  },
  {
    title: 'Sistema de Gestión Hotelera',
    description: 'Aplicación de escritorio con SQL Server Database, usando FXML para la interfaz visual y Java, permitiendo la gestión de reservas de habitaciones, facturación y generación de reportes.',
    image: 'https://images.unsplash.com/photo-1657812159075-7f0abd98f7b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlY29tbWVyY2UlMjB3ZWJzaXRlJTIwaW50ZXJmYWNlfGVufDF8fHx8MTc3NjMwODA2MHww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['Java', 'FXML', 'SQL Server', 'Desktop App'],
    period: 'Proyecto Personal',
    github: 'https://github.com',
    demo: 'https://example.com'
  },
  {
    title: 'Sistema Arcane Restaurant',
    description: 'App para gestión de mesas en restaurante, donde los clientes pueden ordenar escaneando un código QR. Desarrollada con Ionic basado en Angular para el frontend, Fat-Free como backend y MySQL para la base de datos.',
    image: 'https://images.unsplash.com/photo-1707836868495-3307d371aba4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBkZXNpZ24lMjBtb2NrdXB8ZW58MXx8fHwxNzc2MjQ1NzM5fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    technologies: ['Ionic', 'Angular', 'Fat-Free', 'PHP', 'MySQL', 'QR Code'],
    period: 'Proyecto Personal',
    github: 'https://github.com',
    demo: 'https://example.com'
  }
];

export function Projects() {
  return (
    <section id="proyectos" className="py-20 px-4 bg-gradient-to-b from-gray-50 to-white">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Proyectos Destacados
          </h2>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Una selección de mis trabajos más recientes en desarrollo de software. Cada proyecto representa 
            un desafío único y una oportunidad de crear soluciones eficientes e innovadoras.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8">
          {projects.map((project, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
            >
              <Card className="overflow-hidden h-full hover:shadow-xl transition-shadow">
                <div className="relative overflow-hidden group">
                  <ImageWithFallback
                    src={project.image}
                    alt={project.title}
                    className="w-full h-64 object-cover transition-transform duration-300 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                  <div className="absolute bottom-4 left-4 right-4 text-white opacity-0 group-hover:opacity-100 transition-opacity">
                    <p className="text-sm font-medium">{project.period}</p>
                  </div>
                </div>
                
                <div className="p-6">
                  <h3 className="text-xl font-bold mb-2">{project.title}</h3>
                  <p className="text-gray-600 mb-4 text-sm">{project.description}</p>
                  
                  <div className="flex flex-wrap gap-2 mb-4">
                    {project.technologies.map((tech, techIndex) => (
                      <Badge key={techIndex} variant="secondary">
                        {tech}
                      </Badge>
                    ))}
                  </div>

                  <div className="flex gap-3">
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex-1"
                      onClick={() => window.open(project.github, '_blank')}
                    >
                      <Github className="w-4 h-4 mr-2" />
                      Código
                    </Button>
                    <Button
                      size="sm"
                      className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
                      onClick={() => window.open(project.demo, '_blank')}
                    >
                      <ExternalLink className="w-4 h-4 mr-2" />
                      Demo
                    </Button>
                  </div>
                </div>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
